-- MySQL Script generated by MySQL Workbench
-- Fri Jun 14 16:53:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MPRJ
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MPRJ
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MPRJ` DEFAULT CHARACTER SET utf8 ;
USE `MPRJ` ;

-- -----------------------------------------------------
-- Table `MPRJ`.`MonitorAdicional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPRJ`.`MonitorAdicional` (
  `PatrimonioNovo` INT NOT NULL,
  `PatrimonioAntigoMonitor` INT NULL,
  `Serie` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`PatrimonioNovo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPRJ`.`Monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPRJ`.`Monitor` (
  `PatrimonioNovo` INT NOT NULL,
  `PatrimonioAntigoMonitor` INT NOT NULL,
  `Serie` INT NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`PatrimonioNovo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPRJ`.`ImpressoraTermica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPRJ`.`ImpressoraTermica` (
  `PatrimonioNovo` INT NOT NULL,
  `PatrimonioAntigo` INT NULL,
  `Serie` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`PatrimonioNovo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPRJ`.`LeitoOptico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPRJ`.`LeitoOptico` (
  `PatrimonioNovo` INT NOT NULL,
  `PatrimonioAntigo` INT NULL,
  `Serie` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`PatrimonioNovo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPRJ`.`ImpressoraFiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPRJ`.`ImpressoraFiscal` (
  `PatrimonioNovo` INT NOT NULL,
  `PatriminioAntigo` INT NULL,
  `NumeroSerie` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`PatrimonioNovo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPRJ`.`Estabilidazador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPRJ`.`Estabilidazador` (
  `PatrimonioNovo` INT NOT NULL,
  `PatrimonioAntigo` INT NULL,
  `Serie` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`PatrimonioNovo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPRJ`.`Computador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPRJ`.`Computador` (
  `Patrimonio Novo Micro` INT NOT NULL,
  `Patrimonio Antigo Micro` INT NULL,
  `Numero Serie Micro` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `MonitorAdicional_PatrimonioNovo` INT NOT NULL,
  `Monitor_PatrimonioNovo` INT NOT NULL,
  `ImpressoraTermica_PatrimonioNovo` INT NOT NULL,
  `LeitoOptico_PatrimonioNovo` INT NOT NULL,
  `ImpressoraFiscal_PatrimonioNovo` INT NOT NULL,
  `Estabilidazador_PatrimonioNovo` INT NOT NULL,
  PRIMARY KEY (`Patrimonio Novo Micro`),
  INDEX `fk_Computador_MonitorAdicional1_idx` (`MonitorAdicional_PatrimonioNovo` ASC) VISIBLE,
  INDEX `fk_Computador_Monitor1_idx` (`Monitor_PatrimonioNovo` ASC) VISIBLE,
  INDEX `fk_Computador_ImpressoraTermica1_idx` (`ImpressoraTermica_PatrimonioNovo` ASC) VISIBLE,
  INDEX `fk_Computador_LeitoOptico1_idx` (`LeitoOptico_PatrimonioNovo` ASC) VISIBLE,
  INDEX `fk_Computador_ImpressoraFiscal1_idx` (`ImpressoraFiscal_PatrimonioNovo` ASC) VISIBLE,
  INDEX `fk_Computador_Estabilidazador1_idx` (`Estabilidazador_PatrimonioNovo` ASC) VISIBLE,
  CONSTRAINT `fk_Computador_MonitorAdicional1`
    FOREIGN KEY (`MonitorAdicional_PatrimonioNovo`)
    REFERENCES `MPRJ`.`MonitorAdicional` (`PatrimonioNovo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computador_Monitor1`
    FOREIGN KEY (`Monitor_PatrimonioNovo`)
    REFERENCES `MPRJ`.`Monitor` (`PatrimonioNovo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computador_ImpressoraTermica1`
    FOREIGN KEY (`ImpressoraTermica_PatrimonioNovo`)
    REFERENCES `MPRJ`.`ImpressoraTermica` (`PatrimonioNovo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computador_LeitoOptico1`
    FOREIGN KEY (`LeitoOptico_PatrimonioNovo`)
    REFERENCES `MPRJ`.`LeitoOptico` (`PatrimonioNovo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computador_ImpressoraFiscal1`
    FOREIGN KEY (`ImpressoraFiscal_PatrimonioNovo`)
    REFERENCES `MPRJ`.`ImpressoraFiscal` (`PatrimonioNovo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computador_Estabilidazador1`
    FOREIGN KEY (`Estabilidazador_PatrimonioNovo`)
    REFERENCES `MPRJ`.`Estabilidazador` (`PatrimonioNovo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPRJ`.`Comarca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPRJ`.`Comarca` (
  `idComarca` INT NOT NULL AUTO_INCREMENT,
  `Craai` VARCHAR(45) NULL,
  `OrgaoExecusao` VARCHAR(45) NULL,
  `Endereco` VARCHAR(150) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Materia` VARCHAR(45) NULL,
  `Computador_Patrimonio Novo Micro` INT NOT NULL,
  PRIMARY KEY (`idComarca`),
  INDEX `fk_Comarca_Computador1_idx` (`Computador_Patrimonio Novo Micro` ASC) VISIBLE,
  CONSTRAINT `fk_Comarca_Computador1`
    FOREIGN KEY (`Computador_Patrimonio Novo Micro`)
    REFERENCES `MPRJ`.`Computador` (`Patrimonio Novo Micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPRJ`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPRJ`.`Funcionario` (
  `MatFuncionario` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Perfil` VARCHAR(45) NULL,
  `Computador_Patrimonio Novo Micro` INT NOT NULL,
  `Comarca_idComarca` INT NOT NULL,
  PRIMARY KEY (`MatFuncionario`),
  INDEX `fk_Funcionários_Computador_idx` (`Computador_Patrimonio Novo Micro` ASC) VISIBLE,
  INDEX `fk_Funcionário_Comarca1_idx` (`Comarca_idComarca` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionários_Computador`
    FOREIGN KEY (`Computador_Patrimonio Novo Micro`)
    REFERENCES `MPRJ`.`Computador` (`Patrimonio Novo Micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionário_Comarca1`
    FOREIGN KEY (`Comarca_idComarca`)
    REFERENCES `MPRJ`.`Comarca` (`idComarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
